#ifndef EGC_DRIVERS_WIIMOTE_H
#define EGC_DRIVERS_WIIMOTE_H

typedef enum ATTRIBUTE_PACKED {
    EGC_WIIMOTE_EXP_NONE = 0,
    EGC_WIIMOTE_EXP_NUNCHUCK,
    EGC_WIIMOTE_EXP_CLASSIC,
    EGC_WIIMOTE_EXP_CLASSIC_PRO,
    EGC_WIIMOTE_EXP_DRAWSOME_TABLET,
    EGC_WIIMOTE_EXP_GUITAR_HERO_3,
    EGC_WIIMOTE_EXP_GUITAR_HERO_DRUMS,
    EGC_WIIMOTE_EXP_BALANCE_BOARD,
    EGC_WIIMOTE_EXP_DJ_HERO,
    EGC_WIIMOTE_EXP_TAIKO_DRUM,
    EGC_WIIMOTE_EXP_UDRAW_TABLET,
    EGC_WIIMOTE_EXP_SHINKANSEN,
} EgcWiimoteExpType;

#endif /* EGC_DRIVERS_WIIMOTE_H */
